stages:
  - lint
  - test

lint:
  stage: lint
  image: node:20.16.0
  script:
    - npm ci
    - npm run lint

type-check:
  stage: lint
  image: node:20.16.0
  script:
    - npm ci
    - npm run type-check

test:
  stage: test
  image: node:20.16.0
  script:
    - npm ci
    - npm test
