services:
 db:
  image: postgres:16
  restart: unless-stopped
  ports:
    - 65432:5432
  volumes:
    - postgres:/var/lib/postgresql/data
    - ${PWD}/backup/postgres:/var/lib/postgresql/dump:delegated
  environment:
    POSTGRES_USER: demo
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: demo
volumes:
  postgres:
