name: CI

on: [push, pull_request]

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:ci
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> eae3754 (add test to ci)

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'npm'
      - run: npm ci
      - run: npm test
<<<<<<< HEAD
=======
>>>>>>> 2163356 (add CI)
=======
>>>>>>> eae3754 (add test to ci)
